<?php

// NOTE
// just a backup for now

if(!function_exists('acf_add_local_field_group')) return;

acf_add_local_field_group(array(
	'key' => 'group_60f4bf213414e',
	'title' => 'Event Fields',
	'fields' => array(
		array(
			'key' => 'field_60f4bf2737144',
			'label' => 'Event Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60f4bf3537145',
			'label' => 'Start Date',
			'name' => 'start_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'Ymd',
			'first_day' => 0,
		),
		array(
			'key' => 'field_60f4bf5937147',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'm/d/Y',
			'return_format' => 'Ymd',
			'first_day' => 0,
		),
		array(
			'key' => 'field_60f4bf6d4f0f1',
			'label' => 'Is All Day',
			'name' => 'is_all_day',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_60f4bfab02b7f',
			'label' => 'Start Time',
			'name' => 'start_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60f4bf6d4f0f1',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
		array(
			'key' => 'field_60f4bfbd02b80',
			'label' => 'End Time',
			'name' => 'end_time',
			'type' => 'time_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60f4bf6d4f0f1',
						'operator' => '!=',
						'value' => '1',
					),
					array(
						'field' => 'field_60f4bfc402b81',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i a',
			'return_format' => 'g:i a',
		),
		array(
			'key' => 'field_60f4bfc402b81',
			'label' => 'Hide End Time',
			'name' => 'hide_end_time',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60f4bf6d4f0f1',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_60f4c09bbd702',
			'label' => 'Venue',
			'name' => 'venue',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'kritter_venue',
			),
			'taxonomy' => '',
			'allow_null' => 1,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
		array(
			'key' => 'field_60f4c00b18e25',
			'label' => 'Schedule',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60f4c02818e26',
			'label' => 'Recurrence',
			'name' => 'recurrence',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'once' => 'One-time',
				'day' => 'Daily',
				'week' => 'Weekly',
				'month_day' => 'Monthly, days',
				'month_date' => 'Monthly, dates',
				'year' => 'Annually',
				'custom' => 'Custom',
			),
			'allow_null' => 0,
			'default_value' => 'once',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_60f4c20527a23',
			'label' => '',
			'name' => 'recurrence_meta',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60f4c02818e26',
						'operator' => '!=',
						'value' => 'once',
					),
					array(
						'field' => 'field_60f4c02818e26',
						'operator' => '!=',
						'value' => 'custom',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'sub_fields' => array(
				array(
					'key' => 'field_60f4c21927a24',
					'label' => 'Frequency',
					'name' => 'frequency',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => 'Every',
					'append' => '{recurrence}(s)',
					'min' => 1,
					'max' => '',
					'step' => '',
				),
				array(
					'key' => 'field_60f4c3e54a2c5',
					'label' => 'Days',
					'name' => 'week_days',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60f4c02818e26',
								'operator' => '==',
								'value' => 'week',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						0 => 'SUN',
						1 => 'MON',
						2 => 'TUE',
						3 => 'WED',
						4 => 'THU',
						5 => 'FRI',
						6 => 'SAT',
					),
					'allow_custom' => 0,
					'default_value' => array(
					),
					'layout' => 'horizontal',
					'toggle' => 0,
					'return_format' => 'value',
					'save_custom' => 0,
				),
				array(
					'key' => 'field_60f4c4551ad0d',
					'label' => 'Days',
					'name' => 'month_days',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60f4c02818e26',
								'operator' => '==',
								'value' => 'month_day',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array(
						array(
							'key' => 'field_60f4c47b1ad0e',
							'label' => 'SUN',
							'name' => 'sun',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_60f4c4a31ad14',
							'label' => 'MON',
							'name' => 'mon',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_60f4c4a21ad13',
							'label' => 'TUE',
							'name' => 'tue',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_60f4c4a21ad12',
							'label' => 'WED',
							'name' => 'wed',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_60f4c4a11ad11',
							'label' => 'THU',
							'name' => 'thu',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_60f4c4a11ad10',
							'label' => 'FRI',
							'name' => 'fri',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
						array(
							'key' => 'field_60f4c4a01ad0f',
							'label' => 'SAT',
							'name' => 'sat',
							'type' => 'checkbox',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								1 => 'First',
								2 => 'Second',
								3 => 'Third',
								4 => 'Fourth',
								5 => 'Fifth',
								-1 => 'Last',
							),
							'allow_custom' => 0,
							'default_value' => array(
							),
							'layout' => 'vertical',
							'toggle' => 0,
							'return_format' => 'value',
							'save_custom' => 0,
						),
					),
				),
				array(
					'key' => 'field_60f4c4fc55e38',
					'label' => 'Date',
					'name' => 'month_dates',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60f4c02818e26',
								'operator' => '==',
								'value' => 'month_date',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 31,
					'layout' => 'table',
					'button_label' => 'Add Date',
					'sub_fields' => array(
						array(
							'key' => 'field_60f4c5fa55e3a',
							'label' => 'Date',
							'name' => 'date',
							'type' => 'number',
							'instructions' => 'Use 32nd for "last day of month"',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'st/nd/rd/th',
							'min' => 1,
							'max' => 32,
							'step' => '',
						),
					),
				),
				array(
					'key' => 'field_60f4c68241a3b',
					'label' => 'Date',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_60f4c02818e26',
								'operator' => '==',
								'value' => 'year',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'This date will use the Event Details date.',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array(
					'key' => 'field_60f4c2b527a26',
					'label' => 'From',
					'name' => 'schedule_start',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'Ymd',
					'first_day' => 0,
				),
				array(
					'key' => 'field_60f4c3ae27a27',
					'label' => 'Until',
					'name' => 'schedule_end',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'Ymd',
					'first_day' => 0,
				),
				array(
					'key' => 'field_60f4c6cf45c74',
					'label' => 'Summary',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'summary of recurrences',
					'new_lines' => 'wpautop',
					'esc_html' => 0,
				),
			),
		),
		array(
			'key' => 'field_60f4d721a48af',
			'label' => 'Include Dates',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60f4c817f2d6b',
			'label' => 'Included Dates',
			'name' => 'included_dates',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Included Date',
			'sub_fields' => array(
				array(
					'key' => 'field_60f4c81ff2d6c',
					'label' => 'Date',
					'name' => 'date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => '',
					'return_format' => '',
					'first_day' => 0,
				),
			),
		),
		array(
			'key' => 'field_60f4c804f2d6a',
			'label' => 'Exclude Dates',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_60f4c02818e26',
						'operator' => '!=',
						'value' => 'once',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_60f4c82bf2d6d',
			'label' => 'Excluded Dates',
			'name' => 'excluded_dates',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => 'Add Excluded Date',
			'sub_fields' => array(
				array(
					'key' => 'field_60f4c82bf2d6e',
					'label' => 'Date',
					'name' => 'date',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'm/d/Y',
					'return_format' => 'Ymd',
					'first_day' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kritter_event',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_60f4c267bb43c',
	'title' => 'Venue Fields',
	'fields' => array(
		array(
			'key' => 'field_60f4c26bfdc98',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_60f4c272fdc99',
			'label' => 'Map',
			'name' => 'map',
			'type' => 'google_map',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'center_lat' => '',
			'center_lng' => '',
			'zoom' => '',
			'height' => '',
		),
		array(
			'key' => 'field_60f4c283fdc9a',
			'label' => 'Contact',
			'name' => 'contact',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'kritter_venue',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));
